#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t lineage"

$L "..........................................."
$L "                                           "
$L "                Be-Delighted               "
$L "                                           "
$L "..........................................."
$L "Welcome to Android `getprop ro.build.version.release` / LineageOS-`getprop ro.lineage.version`";
